[project]
name = "microalpha"
version = "0.1.0"
description = "A event-driven backtesting engine for quantitative strategies."
authors = [
    { name = "Mateo Bodon", email = "mateo.bodon@yale.edu" },
]
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "numpy",
    "pytest",
    "ruff",
    "black",
    "pyyaml",
]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
exclude = [
    "notebooks/**",
    ".ipynb_checkpoints/**",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = [
    # Temporarily ignore long lines in CI to unblock; keep Black for wrapping
    "E501",
]

[tool.setuptools]
packages = ["microalpha"]