# Configuration for a Breakout strategy run (BacktestCfg schema)

data_path: "../data"
symbol: "SPY"
cash: 100000.0
seed: 42

exec:
  type: "twap"
  commission: 0.5
  slices: 4

strategy:
  name: "BreakoutStrategy"
  params:
    lookback: 5