# Configuration for a Breakout strategy run (unified schema)

data_path: "data"
symbol: "SPY"
cash: 100000.0
seed: 42

exec:
  type: "twap"
  commission: 0.1
  slices: 4

strategy:
  name: "BreakoutStrategy"
  params:
    lookback: 5
    exit_lookback: 5
    time_stop: 5