# Configuration for a Breakout strategy run

backtest_settings:
    symbol: "SPY"
    initial_cash: 100000.0
    data_dir: "data"

strategy:
    name: "BreakoutStrategy"
    params:
        lookback: 5

broker_settings:
    execution_style: "TWAP"
    num_ticks: 4

# Seed for reproducibility
random_seed: 42