# Configuration for a Mean Reversion strategy run

data_path: "../data"
symbol: "SPY"
cash: 100000.0
seed: 42

exec:
  type: "twap"
  aln: 0.5
  price_impact: 0.00005

strategy:
  name: "MeanReversionStrategy"
  lookback: 3
  z: 0.5
