# Configuration for a Mean Reversion strategy run

data_path: "../data"
symbol: "SPY"
cash: 100000.0
seed: 42
max_exposure: 0.6
max_drawdown_stop: 0.25
turnover_cap: 500000.0
kelly_fraction: 0.05

exec:
  type: "twap"
  commission: 0.5
  price_impact: 0.00005
  slices: 4
  slippage:
    type: "volume"
    impact: 0.0001

strategy:
  name: "MeanReversionStrategy"
  params:
    lookback: 2
    z_threshold: 0.2

capital_policy:
  type: "volatility_scaled"
  lookback: 5
  target_dollar_vol: 15000.0
  min_qty: 5
