# Walk-forward validation for cross-sectional momentum

template:
  data_path: "../data"
  symbols: ["SPY", "AAPL", "MSFT", "GOOG", "AMZN", "META", "NVDA", "TSLA", "JPM", "V"]
  cash: 1000000.0
  seed: 7
  exec:
    type: "twap"
    commission_bps: 1.0
    slices: 2
  strategy:
    name: "CrossSectionalMomentum"
    params: { lookback_months: 12, skip_months: 1, top_frac: 0.3, vol_target: 0.10 }

walkforward:
  start: "2015-01-01"
  end: "2020-12-31"
  training_days: 252
  testing_days: 63

grid:
  lookback_months: [6, 9, 12]
  top_frac: [0.2, 0.3, 0.4]


