template:
  data_path: ../data_sp500
  cash: 1000000.0
  seed: 7
  exec:
    type: twap
    commission_bps: 1.0
    slices: 2
  strategy:
    name: CrossSectionalMomentum
    params:
      lookback_months: 12
      skip_months: 1
      top_frac: 0.3
      vol_target: 0.1
  universe_path: /Users/mateobodon/Documents/Programming/Projects/microalpha/sp500_tickers_from_export.txt
walkforward:
  start: '2015-01-01'
  end: '2020-12-31'
  training_days: 252
  testing_days: 63
grid:
  lookback_months:
  - 6
  - 9
  - 12
  top_frac:
  - 0.2
  - 0.3
  - 0.4
