# Walk-forward validation for cross-sectional momentum (12-1, monthly rebalance)

template:
  data_path: "data_sp500"
  symbol: "SPY"  # fallback benchmark symbol
  cash: 1000000.0
  seed: 7
  exec:
    type: "twap"
    commission: 0.0005
    slices: 2
  strategy:
    name: "CrossSectionalMomentum"
    params:
      symbols: ["AAPL", "MSFT", "GOOG", "AMZN", "META", "NVDA", "TSLA", "JPM", "V", "SPY"]
      lookback_months: 12
      skip_months: 1
      top_frac: 0.3

walkforward:
  start: "2018-01-01"
  end: "2020-12-31"
  training_days: 252
  testing_days: 63

grid:
  lookback_months: [9, 12]
  top_frac: [0.2, 0.3, 0.4]

artifacts_dir: "artifacts"


