# Walk-forward validation for cross-sectional momentum on small bundled dataset

template:
  data_path: "data_sp500"
  symbol: "SPY"
  cash: 1000000.0
  seed: 7
  exec:
    type: "twap"
    commission: 0.0005
    slices: 2
  strategy:
    name: "CrossSectionalMomentum"
    params:
      symbols: ["AAPL", "AMZN", "GOOG", "JPM", "META", "MSFT", "NVDA", "TSLA", "V"]
      lookback_months: 12
      skip_months: 1
      top_frac: 0.3

walkforward:
  start: "2018-01-01"
  end: "2020-12-31"
  training_days: 252
  testing_days: 63

grid:
  lookback_months: [6, 9, 12]
  skip_months: [0, 1]
  top_frac: [0.2, 0.3, 0.4]

artifacts_dir: "artifacts"
