# Walk-forward validation using bundled public ticker samples (AAPL, MSFT, etc.)

template:
  data_path: "data/public/prices"
  meta_path: "data/public/meta_public.csv"
  symbol: "AAPL"
  cash: 1000000.0
  seed: 123
  max_exposure: 1.5
  max_drawdown_stop: 0.3
  max_portfolio_heat: 3.0
  metrics_hac_lags: 5
  exec:
    type: "twap"
    commission: 0.0005
    slices: 2
    limit_mode: "ioc"
    queue_coefficient: 0.1
    queue_passive_multiplier: 0.4
    queue_seed: 2025
  strategy:
    name: "FlagshipMomentumStrategy"
    allocator: "budgeted_rp"
    allocator_params:
      risk_model: "risk_parity"
    params:
      universe_path: "data/public/universe_public.csv"
      lookback_months: 3
      skip_months: 1
      top_frac: 0.5
      bottom_frac: 0.3
      max_positions_per_sector: 2
      turnover_target_pct_adv: 0.15
      min_adv: 1500000.0
      min_price: 80.0
      total_risk_budget: 1.0
  capital_policy:
    type: "volatility_scaled"
    lookback: 21
    target_dollar_vol: 20000.0
    min_qty: 1

walkforward:
  start: "2024-01-02"
  end: "2024-01-12"
  training_days: 4
  testing_days: 2

grid:
  top_frac: [0.4, 0.6]
  skip_months: [0, 1]

reality_check:
  method: "stationary"
  samples: 200
  block_length: 3
